name: UpdateTimeJson

on:
  push:
    branches:
      - main
    paths:
      - 'MaaAssistantArknights/api/gui/StageActivity.json'
      - 'MaaAssistantArknights/api/resource/**'
  workflow_dispatch:

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Version Name
        id: version_name
        run: |
          version=$(date --utc +%Y%m%d%H%M%S)
          echo "version=$version" | tee -a "$GITHUB_OUTPUT"
          
          echo $version | jq -c '{timestamp:.}' | tee MaaAssistantArknights/api/stageAndTasksUpdateTime.json
          echo $version | jq -c '{timestamp:.}' | tee MaaAssistantArknights/api/lastUpdateTime.json

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
